apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    component: frontend
spec:
  containers:
    - name: frontend
      image: 598125288280.dkr.ecr.us-east-1.amazonaws.com/frontend:2.1.0
      
      
      
      
      